import { readSettings } from "./settings";

export interface DeployConfig {
  appName: string;
  runId: string;
  appDir: string;
}

export interface DeployResult {
  success: boolean;
  appUuid?: string;
  deploymentUrl?: string;
  githubRepoUrl?: string;
  error?: string;
  steps: DeployStep[];
}

interface DeployStep {
  name: string;
  status: "success" | "failed" | "skipped";
  message: string;
}

const DEFAULT_SERVER_UUID = "nksk84gkwog0s4w0g4scwko4";
const DEFAULT_PROJECT_UUID = "ce0ih9q54ua6f5d6ygpr99h8";

/**
 * Deploy a generated app to Coolify via GitHub + Coolify API.
 *
 * Flow:
 * 1. Create GitHub repo
 * 2. Push code to repo
 * 3. Create Coolify application from repo
 * 4. Return deployment info
 */
export async function deployGeneratedApp(
  config: DeployConfig
): Promise<DeployResult> {
  const steps: DeployStep[] = [];
  const settings = readSettings();

  // Validate credentials
  if (!settings.coolifyApiUrl || !settings.coolifyApiToken) {
    return {
      success: false,
      error: "Coolify API credentials not configured",
      steps: [{ name: "validate", status: "failed", message: "coolifyApiUrl or coolifyApiToken missing" }],
    };
  }

  if (!settings.githubToken) {
    return {
      success: false,
      error: "GitHub token not configured",
      steps: [{ name: "validate", status: "failed", message: "githubToken missing" }],
    };
  }

  steps.push({ name: "validate", status: "success", message: "Credentials validated" });

  // 1. Create GitHub repo
  const repoName = sanitizeRepoName(config.appName);
  const githubOrg = settings.githubOrg || "";

  const createUrl = githubOrg
    ? `https://api.github.com/orgs/${githubOrg}/repos`
    : "https://api.github.com/user/repos";

  let repoHtmlUrl = "";
  let ownerLogin = "";

  try {
    const repoRes = await fetch(createUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${settings.githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        private: false,
        auto_init: false,
        description: `Generated by AI App Factory — ${config.appName}`,
      }),
    });

    const repoData = (await repoRes.json()) as {
      html_url?: string;
      clone_url?: string;
      owner?: { login: string };
      message?: string;
      errors?: { message?: string }[];
    };

    if (!repoRes.ok || !repoData.html_url) {
      // If repo already exists (422), try to use it
      const errMessages = [repoData.message, ...(repoData.errors?.map(e => e.message) || [])].join(" ");
      if (repoRes.status === 422 && (errMessages.includes("already exists") || errMessages.includes("creation failed"))) {
        // Fetch existing repo info
        const owner = githubOrg || (await fetch("https://api.github.com/user", {
          headers: { Authorization: `Bearer ${settings.githubToken}`, Accept: "application/vnd.github.v3+json" },
        }).then(r => r.json()).then((d: { login: string }) => d.login));

        repoHtmlUrl = `https://github.com/${owner}/${repoName}`;
        ownerLogin = owner;
        steps.push({ name: "github_create", status: "success", message: `Mevcut repo kullanılıyor: ${repoHtmlUrl}` });
      } else {
        steps.push({
          name: "github_create",
          status: "failed",
          message: repoData.message || `HTTP ${repoRes.status}`,
        });
        return { success: false, error: `GitHub repo oluşturulamadı: ${repoData.message}`, steps };
      }
    } else {
      repoHtmlUrl = repoData.html_url;
      ownerLogin = repoData.owner?.login || githubOrg;
      steps.push({ name: "github_create", status: "success", message: repoHtmlUrl });
    }
  } catch (e) {
    steps.push({ name: "github_create", status: "failed", message: String(e) });
    return { success: false, error: `GitHub API error: ${e}`, steps };
  }

  // 2. Push code to GitHub (via shell — git operations)
  try {
    const { execSync } = await import("child_process");
    const fs = await import("fs");
    const path = await import("path");
    const pushUrl = `https://${settings.githubToken}@github.com/${ownerLogin}/${repoName}.git`;

    // Ensure the app directory exists
    if (!fs.existsSync(config.appDir)) {
      steps.push({ name: "github_push", status: "failed", message: `App directory not found: ${config.appDir}` });
      return { success: false, error: `App dizini bulunamadı: ${config.appDir}`, githubRepoUrl: repoHtmlUrl, steps };
    }

    // Remove existing .git directory if present (clean state)
    const gitDir = path.join(config.appDir, ".git");
    if (fs.existsSync(gitDir)) {
      execSync(`rm -rf "${gitDir}"`, { stdio: "pipe" });
    }

    // Create .gitignore if missing
    const gitignorePath = path.join(config.appDir, ".gitignore");
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, "node_modules/\n.next/\n.env\n.env.local\n");
    }

    // Run git commands step by step for better error reporting
    const gitExec = (cmd: string) =>
      execSync(cmd, {
        cwd: config.appDir,
        stdio: "pipe",
        timeout: 60_000,
        env: { ...process.env, GIT_TERMINAL_PROMPT: "0", HOME: "/tmp" },
      }).toString().trim();

    // Set safe.directory BEFORE git init (required when dir owned by different user)
    try {
      execSync(`git config --global --add safe.directory "${config.appDir}"`, {
        stdio: "pipe",
        timeout: 10_000,
        env: { ...process.env, HOME: "/tmp" },
      });
    } catch {
      // Fallback: set via GIT_CONFIG_GLOBAL
      fs.writeFileSync("/tmp/.gitconfig", `[safe]\n\tdirectory = ${config.appDir}\n`);
    }

    gitExec("git init -b main");
    gitExec('git config user.email "factory@seymata.com"');
    gitExec('git config user.name "AI App Factory"');
    gitExec("git add -A");
    gitExec('git commit -m "feat: initial commit — generated by AI App Factory"');
    gitExec(`git remote add origin "${pushUrl}"`);
    // Use force push in case repo already has content (re-deploy scenario)
    gitExec("git push -u origin main --force");

    steps.push({ name: "github_push", status: "success", message: "Code pushed to GitHub" });
  } catch (e: unknown) {
    const errMsg = e instanceof Error
      ? (e as { stderr?: Buffer }).stderr?.toString() || e.message
      : String(e);
    steps.push({ name: "github_push", status: "failed", message: errMsg.slice(0, 500) });
    return { success: false, error: `GitHub push hatası: ${errMsg.slice(0, 300)}`, githubRepoUrl: repoHtmlUrl, steps };
  }

  // 3. Create Coolify application
  const serverUuid = settings.coolifyServerUuid || DEFAULT_SERVER_UUID;
  const projectUuid = settings.coolifyProjectUuid || DEFAULT_PROJECT_UUID;
  const coolifyBaseUrl = settings.coolifyApiUrl.replace(/\/+$/, "");

  let appUuid = "";

  try {
    const appRes = await fetch(`${coolifyBaseUrl}/api/v1/applications/public`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${settings.coolifyApiToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        project_uuid: projectUuid,
        server_uuid: serverUuid,
        environment_name: "production",
        git_repository: repoHtmlUrl,
        git_branch: "main",
        build_pack: "dockerfile",
        ports_exposes: "3000",
        health_check_enabled: true,
        health_check_path: "/api/health",
        instant_deploy: true,
        name: repoName,
      }),
    });

    const appData = (await appRes.json()) as {
      uuid?: string;
      message?: string;
    };

    if (!appRes.ok || !appData.uuid) {
      steps.push({
        name: "coolify_create",
        status: "failed",
        message: appData.message || `HTTP ${appRes.status}`,
      });
      return {
        success: false,
        error: `Coolify app creation failed: ${appData.message}`,
        githubRepoUrl: repoHtmlUrl,
        steps,
      };
    }

    appUuid = appData.uuid;
    steps.push({ name: "coolify_create", status: "success", message: `App UUID: ${appUuid}` });
  } catch (e) {
    steps.push({ name: "coolify_create", status: "failed", message: String(e) });
    return {
      success: false,
      error: `Coolify API error: ${e}`,
      githubRepoUrl: repoHtmlUrl,
      steps,
    };
  }

  return {
    success: true,
    appUuid,
    githubRepoUrl: repoHtmlUrl,
    steps,
  };
}

function sanitizeRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 50);
}
