import { readSettings } from "./settings";

export interface VercelDeployConfig {
  appName: string;
  runId: string;
  appDir: string;
}

export interface VercelDeployResult {
  success: boolean;
  projectId?: string;
  deploymentUrl?: string;
  githubRepoUrl?: string;
  dashboardUrl?: string;
  error?: string;
  steps: DeployStep[];
}

interface DeployStep {
  name: string;
  status: "success" | "failed" | "skipped";
  message: string;
}

const VERCEL_TEAM_ID = "team_xSNPPRu1DkUfzby6KCuYn2oE";

/**
 * Deploy a generated app to Vercel via GitHub + Vercel API.
 *
 * Flow:
 * 1. Create GitHub repo (or use existing)
 * 2. Push code to repo
 * 3. Create Vercel project from GitHub repo (auto-deploy)
 * 4. Return deployment URL
 */
export async function deployToVercel(
  config: VercelDeployConfig
): Promise<VercelDeployResult> {
  const steps: DeployStep[] = [];
  const settings = readSettings();

  // Validate credentials
  if (!settings.githubToken) {
    return {
      success: false,
      error: "GitHub token ayarlanmamış. /settings sayfasından ekleyin.",
      steps: [{ name: "validate", status: "failed", message: "githubToken missing" }],
    };
  }

  // Vercel token from env or settings
  const vercelToken = process.env.VERCEL_TOKEN || settings.vercelToken || "";
  if (!vercelToken) {
    return {
      success: false,
      error: "Vercel token ayarlanmamış. VERCEL_TOKEN env var veya settings'e ekleyin.",
      steps: [{ name: "validate", status: "failed", message: "vercelToken missing" }],
    };
  }

  steps.push({ name: "validate", status: "success", message: "Credentials validated" });

  // 1. Create GitHub repo
  const repoName = sanitizeRepoName(config.appName);
  const githubOrg = settings.githubOrg || "";

  const createUrl = githubOrg
    ? `https://api.github.com/orgs/${githubOrg}/repos`
    : "https://api.github.com/user/repos";

  let repoFullName = "";
  let repoHtmlUrl = "";

  try {
    const repoRes = await fetch(createUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${settings.githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        private: false,
        auto_init: false,
        description: `Generated by AI App Factory — ${config.appName}`,
      }),
    });

    const repoData = (await repoRes.json()) as {
      html_url?: string;
      full_name?: string;
      owner?: { login: string };
      message?: string;
      errors?: { message?: string }[];
    };

    const errMessages = [repoData.message, ...(repoData.errors?.map(e => e.message) || [])].join(" ");
    if (repoRes.status === 422 && (errMessages.includes("already exists") || errMessages.includes("creation failed"))) {
      // Use existing repo
      const owner = githubOrg || await getGitHubUsername(settings.githubToken);
      repoFullName = `${owner}/${repoName}`;
      repoHtmlUrl = `https://github.com/${repoFullName}`;
      steps.push({ name: "github_create", status: "success", message: `Mevcut repo: ${repoHtmlUrl}` });
    } else if (!repoRes.ok || !repoData.html_url) {
      steps.push({ name: "github_create", status: "failed", message: repoData.message || `HTTP ${repoRes.status}` });
      return { success: false, error: `GitHub repo oluşturulamadı: ${repoData.message}`, steps };
    } else {
      repoHtmlUrl = repoData.html_url;
      repoFullName = repoData.full_name || `${repoData.owner?.login}/${repoName}`;
      steps.push({ name: "github_create", status: "success", message: repoHtmlUrl });
    }
  } catch (e) {
    steps.push({ name: "github_create", status: "failed", message: String(e) });
    return { success: false, error: `GitHub API hatası: ${e}`, steps };
  }

  // 2. Push code to GitHub
  try {
    const { execSync } = await import("child_process");
    const fs = await import("fs");
    const path = await import("path");
    const [owner, repo] = repoFullName.split("/");
    const pushUrl = `https://${settings.githubToken}@github.com/${owner}/${repo}.git`;

    if (!fs.existsSync(config.appDir)) {
      steps.push({ name: "github_push", status: "failed", message: `App dizini bulunamadı: ${config.appDir}` });
      return { success: false, error: `App dizini bulunamadı: ${config.appDir}`, githubRepoUrl: repoHtmlUrl, steps };
    }

    // Remove existing .git
    const gitDir = path.join(config.appDir, ".git");
    if (fs.existsSync(gitDir)) {
      execSync(`rm -rf "${gitDir}"`, { stdio: "pipe" });
    }

    // Create .gitignore if missing
    const gitignorePath = path.join(config.appDir, ".gitignore");
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, "node_modules/\n.next/\n.env\n.env.local\n.vercel/\n");
    }

    // Create vercel.json for proper Next.js config
    const vercelJsonPath = path.join(config.appDir, "vercel.json");
    if (!fs.existsSync(vercelJsonPath)) {
      fs.writeFileSync(vercelJsonPath, JSON.stringify({
        framework: "nextjs",
        buildCommand: "pnpm run build",
        installCommand: "pnpm install",
      }, null, 2));
    }

    const gitExec = (cmd: string) =>
      execSync(cmd, {
        cwd: config.appDir,
        stdio: "pipe",
        timeout: 60_000,
        env: { ...process.env, GIT_TERMINAL_PROMPT: "0", HOME: "/tmp" },
      }).toString().trim();

    // Set safe.directory BEFORE git init (required when dir owned by different user)
    try {
      execSync(`git config --global --add safe.directory "${config.appDir}"`, {
        stdio: "pipe",
        timeout: 10_000,
        env: { ...process.env, HOME: "/tmp" },
      });
    } catch {
      // Fallback: set via GIT_CONFIG_GLOBAL
      fs.writeFileSync("/tmp/.gitconfig", `[safe]\n\tdirectory = ${config.appDir}\n`);
    }

    gitExec("git init -b main");
    gitExec('git config user.email "factory@seymata.com"');
    gitExec('git config user.name "AI App Factory"');
    gitExec("git add -A");
    gitExec('git commit -m "feat: initial commit — generated by AI App Factory"');
    gitExec(`git remote add origin "${pushUrl}"`);
    gitExec("git push -u origin main --force");

    steps.push({ name: "github_push", status: "success", message: "Code pushed to GitHub" });
  } catch (e: unknown) {
    const errMsg = e instanceof Error
      ? (e as { stderr?: Buffer }).stderr?.toString() || e.message
      : String(e);
    steps.push({ name: "github_push", status: "failed", message: errMsg.slice(0, 500) });
    return { success: false, error: `GitHub push hatası: ${errMsg.slice(0, 300)}`, githubRepoUrl: repoHtmlUrl, steps };
  }

  // 3. Create Vercel project from GitHub repo
  let projectId = "";
  let deploymentUrl = "";

  try {
    // Check if project already exists
    const existingRes = await fetch(
      `https://api.vercel.com/v9/projects/${repoName}?teamId=${VERCEL_TEAM_ID}`,
      { headers: { Authorization: `Bearer ${vercelToken}` } }
    );

    if (existingRes.ok) {
      const existingData = (await existingRes.json()) as { id: string };
      projectId = existingData.id;
      steps.push({ name: "vercel_project", status: "success", message: `Mevcut proje: ${projectId}` });

      // Trigger a new deployment by creating a deployment
      const deployRes = await fetch(
        `https://api.vercel.com/v13/deployments?teamId=${VERCEL_TEAM_ID}`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${vercelToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            name: repoName,
            project: projectId,
            gitSource: {
              type: "github",
              ref: "main",
              repoId: repoFullName,
            },
          }),
        }
      );

      if (deployRes.ok) {
        const deployData = (await deployRes.json()) as { url?: string; id?: string };
        deploymentUrl = deployData.url ? `https://${deployData.url}` : "";
      }
    } else {
      // Create new project from GitHub
      const createRes = await fetch(
        `https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM_ID}`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${vercelToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            name: repoName,
            framework: "nextjs",
            gitRepository: {
              type: "github",
              repo: repoFullName,
            },
            buildCommand: "pnpm run build",
            installCommand: "pnpm install",
          }),
        }
      );

      const createData = (await createRes.json()) as {
        id?: string;
        error?: { message: string };
        link?: { deployHooks?: { url: string }[] };
      };

      if (!createRes.ok || !createData.id) {
        const errMsg = createData.error?.message || `HTTP ${createRes.status}`;
        steps.push({ name: "vercel_project", status: "failed", message: errMsg });
        return {
          success: false,
          error: `Vercel proje oluşturulamadı: ${errMsg}`,
          githubRepoUrl: repoHtmlUrl,
          steps,
        };
      }

      projectId = createData.id;
      steps.push({ name: "vercel_project", status: "success", message: `Yeni proje: ${projectId}` });
    }

    // Get latest deployment URL
    if (!deploymentUrl) {
      // Wait briefly, then check deployments
      await new Promise((r) => setTimeout(r, 3000));
      const deploymentsRes = await fetch(
        `https://api.vercel.com/v6/deployments?projectId=${projectId}&teamId=${VERCEL_TEAM_ID}&limit=1`,
        { headers: { Authorization: `Bearer ${vercelToken}` } }
      );
      if (deploymentsRes.ok) {
        const deploymentsData = (await deploymentsRes.json()) as {
          deployments?: { url?: string; state?: string }[];
        };
        const latest = deploymentsData.deployments?.[0];
        if (latest?.url) {
          deploymentUrl = `https://${latest.url}`;
        }
      }
    }

    steps.push({
      name: "vercel_deploy",
      status: "success",
      message: deploymentUrl || "Deploy başlatıldı — Vercel dashboard'dan takip edin",
    });

  } catch (e) {
    steps.push({ name: "vercel_project", status: "failed", message: String(e) });
    return {
      success: false,
      error: `Vercel API hatası: ${e}`,
      githubRepoUrl: repoHtmlUrl,
      steps,
    };
  }

  return {
    success: true,
    projectId,
    deploymentUrl,
    githubRepoUrl: repoHtmlUrl,
    dashboardUrl: `https://vercel.com/${VERCEL_TEAM_ID}/${repoName}`,
    steps,
  };
}

async function getGitHubUsername(token: string): Promise<string> {
  const res = await fetch("https://api.github.com/user", {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github.v3+json" },
  });
  const data = (await res.json()) as { login: string };
  return data.login;
}

function sanitizeRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 50);
}
